### ISSUE TITLE
Binnie's Bees

### ISSUE THREAD

**Issue by Ruidolph** [ForestryMC/Binnie#403] opened 2018-01-26 21:24 UTC
Acclimatized a bred embittered queen so she got down 1 on her heat temperatures and it resulted in this crash: 
Time: 1/26/18 9:06 PM
Description: Ticking block entity

java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:295)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:252)
	at forestry.apiculture.tiles.TileBeeHousingBase.updateServerSide(TileBeeHousingBase.java:151)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:86)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

My mod list is: Direwolf FTB 1.12.2 version 1.7.1 with AbyssalCraft & Abyssalcraft Integration, EvilCraft, Animania, Ice and Fire, Buildcraft & Buildcraft Compat, MCA, and More Bees.

Is there anyway to fix this to prevent this from reoccuring again?

**Comment by Nedelosk** [comment] 2018-01-26 21:28
Duplicate of #370

**Closed as completed by Nedelosk** 2018-01-26 21:28 UTC
Labels: duplicate
