### ISSUE TITLE
Crashing when opening game (1.12.2)

### ISSUE THREAD

**Issue by MythicalOre** [ForestryMC/Binnie#667] opened 2021-05-27 08:02 UTC
HELP, my game keep crashing and it seems binnie was the cause 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
  RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/27/21 2:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Binnie's Genetics (genetics)
Caused by: java.lang.IllegalStateException: Could not fill fluid handler for container: CAPSULE
	at binnie.core.liquid.FluidContainerType.getFilled(FluidContainerType.java:85)
	at binnie.genetics.machine.acclimatiser.Acclimatiser.setupRecipes(Acclimatiser.java:144)
	at binnie.genetics.modules.ModuleMachine.doInit(ModuleMachine.java:95)
	at binnie.core.modules.ModuleContainer.runInit(ModuleContainer.java:67)
	at binnie.core.modules.BlankModuleContainer.init(BlankModuleContainer.java:26)
	at binnie.genetics.Genetics.init(Genetics.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3565845592 bytes (3400 MB) / 6308233216 bytes (6016 MB) up to 6308233216 bytes (6016 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx6014M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 116 mods loaded, 116 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                  | Source                                            | Signature                                |
	|:----- |:-------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                  | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCHI  | mcp                        | 9.42                     | minecraft.jar                                     | None                                     |
	| LCHI  | FML                        | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                      | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | foamfixcore                | 7.7.4                    | minecraft.jar                                     | None                                     |
	| LCHI  | randompatches              | 1.12.2-1.15.0.2          | randompatches-1.12.2-1.15.0.2.jar                 | None                                     |
	| LCHI  | ctm                        | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LCHI  | appliedenergistics2        | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHI  | mantle                     | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                          | None                                     |
	| LCHI  | chisel                     | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCHI  | crafttweaker               | 4.1.16                   | CraftTweaker2-1.12-4.1.16.jar                     | None                                     |
	| LCHI  | mtlib                      | 3.0.6                    | MTLib-3.0.6.jar                                   | None                                     |
	| LCHI  | modtweaker                 | 4.0.16                   | modtweaker-4.0.16.jar                             | None                                     |
	| LCHI  | jei                        | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LCHI  | tinkersextras              | 1.12.2-1.0.9             | TinkersExtras-1.12.2-1.0.9.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | tconstruct                 | 1.12.2-2.12.0.123        | TConstruct-1.12.2-2.12.0.123.jar                  | None                                     |
	| LCHI  | p455w0rdslib               | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                    | None                                     |
	| LCHI  | ae2wtlib                   | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                         | None                                     |
	| LCHI  | appleskin                  | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| LCHI  | badwithernocookiereloaded  | 1.12.2-3.3.16            | badwithernocookiereloaded-1.12.2-3.3.16.jar       | None                                     |
	| LCHI  | base                       | 3.12.0                   | base-1.12.2-3.12.0.jar                            | None                                     |
	| LCHI  | forestry                   | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
	| LCHI  | beebetteratbees            | 2.0.3                    | beebetteratbees-1.12.2-2.0.3.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHI  | betterbuilderswands        | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
	| LCHI  | bettermobgriefinggamerule  | 1.12.2-7.0.1             | bettermobgriefinggamerule-1.12.2-7.0.1.jar        | None                                     |
	| LCHI  | betterquesting             | 3.5.287                  | BetterQuesting-3.5.287.jar                        | None                                     |
	| LCHI  | biggerpacketsplz           | 1.2                      | biggerpacketsplz-since1.8-1.2.jar                 | 266588b191a3e2974a4a577f282858a3bc07da42 |
	| LCHI  | binniecore                 | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                  | None                                     |
	| LCHI  | binniedesign               | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                  | None                                     |
	| LCHE  | genetics                   | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                  | None                                     |
	| LCH   | botany                     | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                  | None                                     |
	| LCH   | extrabees                  | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                  | None                                     |
	| LCH   | extratrees                 | 2.5.1.203                | binnie-mods-1.12.2-2.5.1.203.jar                  | None                                     |
	| LCH   | blockcraftery              | 1.12.2-1.2.0             | blockcraftery-1.12.2-1.2.0.jar                    | None                                     |
	| LCH   | buildinggadgets            | 2.6.8                    | BuildingGadgets-2.6.8.jar                         | None                                     |
	| LCH   | carryon                    | 1.12.1                   | CarryOn MC1.12.2 v1.12.1.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCH   | ceramics                   | 1.12-1.3.6               | Ceramics-1.12-1.3.6.jar                           | None                                     |
	| LCH   | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCH   | clumps                     | 3.1.2                    | Clumps-3.1.2.jar                                  | None                                     |
	| LCH   | codechickenlib             | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | consolefilter              | 1.1.1                    | ConsoleFilter-1.12.2-1.1.1.jar                    | None                                     |
	| LCH   | containerfix               | 1.0                      | ContainerFix MC1.12.2 v1.0.jar                    | None                                     |
	| LCH   | contenttweaker             | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                   | None                                     |
	| LCH   | controlling                | 3.0.6                    | Controlling-3.0.6.jar                             | None                                     |
	| LCH   | craftingtweaks             | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                   | None                                     |
	| LCH   | ctgui                      | 1.0.0                    | CraftTweaker2-1.12-4.1.16.jar                     | None                                     |
	| LCH   | crafttweakerjei            | 2.0.2                    | CraftTweaker2-1.12-4.1.16.jar                     | None                                     |
	| LCH   | custommainmenu             | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                 | None                                     |
	| LCH   | defaultoptions             | 9.2.8                    | DefaultOptions_1.12.2-9.2.8.jar                   | None                                     |
	| LCH   | defaultworldgenerator-port | 1.12-2.3                 | DefaultWorldGenerator-port-1.12-2.3.jar           | None                                     |
	| LCH   | forgelin                   | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
	| LCH   | exnihilocreatio            | 1.12.2-0.3.9             | exnihilocreatio-1.12.2-0.3.9.jar                  | None                                     |
	| LCH   | excompressum               | 3.0.26                   | ExCompressum_1.12.2-3.0.26.jar                    | None                                     |
	| LCH   | extracells                 | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                      | None                                     |
	| LCH   | fastfurnace                | 1.2.2                    | FastFurnace-1.12.2-1.2.2.jar                      | None                                     |
	| LCH   | fastleafdecay              | v14                      | FastLeafDecay-v14.jar                             | None                                     |
	| LCH   | fastbench                  | 1.6.1                    | FastWorkbench-1.12.2-1.6.1.jar                    | None                                     |
	| LCH   | findme                     | 1.1.0                    | findme-1.12.2-1.1.0-8.jar                         | None                                     |
	| LCH   | floodlights                | 1.3.2-14                 | FloodLights-1.12.2-1.3.2-14.jar                   | None                                     |
	| LCH   | foamfix                    | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                         | None                                     |
	| LCH   | forgemultipartcbe          | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | microblockcbe              | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCH   | minecraftmultipartcbe      | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar      | None                                     |
	| LCH   | forgivingvoid              | 1.0.21                   | ForgivingVoid_1.12.2-1.0.21.jar                   | None                                     |
	| LCH   | ftblib                     | 5.4.1.93                 | FTBLib-5.4.1.93.jar                               | None                                     |
	| LCH   | ftbutilities               | 5.4.0.88                 | FTBUtilities-5.4.0.88.jar                         | None                                     |
	| LCH   | ftbbackups                 | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.2.jar                   | None                                     |
	| LCH   | trashcansreborn            | 1.1.0                    | GarbageBins-1.1.1.jar                             | None                                     |
	| LCH   | gregtech                   | 1.6.6.374                | gregtech-1.12.2-1.6.6.374.jar                     | None                                     |
	| LCH   | gtadditions                | 1.12.2-1.4.2             | GregicAdditions-1.12.2-1.4.2.jar                  | None                                     |
	| LCH   | gregblockutils             | 1.12.2-1.2.2             | GregBlockUtilities-1.12.2-1.2.2.jar               | None                                     |
	| LCH   | gtconstruct                | 1.12.2-1.0.1             | GregsConstruct-1.12.2-1.0.1.jar                   | None                                     |
	| LCH   | gtcebees                   | 1.12.2-1.0.3             | GTCEBees-1.12.2-1.0.3.jar                         | None                                     |
	| LCH   | incontrol                  | 3.9.6                    | incontrol-1.12-3.9.6.jar                          | None                                     |
	| LCH   | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | itlt                       | 1.0.0                    | itlt-1.12-1.0.0.jar                               | None                                     |
	| LCH   | jeibees                    | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
	| LCH   | kleeslabs                  | 5.4.11                   | KleeSlabs_1.12.2-5.4.11.jar                       | None                                     |
	| LCH   | moreoverlays               | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                    | None                                     |
	| LCH   | morpheus                   | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
	| LCH   | mousetweaks                | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
	| LCH   | mrtjpcore                  | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar           | None                                     |
	| LCH   | nmsot                      | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar           | None                                     |
	| LCH   | nuclearcraft               | 2.14c                    | NuclearCraft-2.14c-1.12.2.jar                     | None                                     |
	| LCH   | oreexcavation              | 1.4.137                  | OreExcavation-1.4.137.jar                         | None                                     |
	| LCH   | packagedauto               | 1.12.2-1.0.1.4           | PackagedAuto-1.12.2-1.0.1.5.jar                   | None                                     |
	| LCH   | placebo                    | 1.5.1                    | Placebo-1.12.2-1.5.1.jar                          | None                                     |
	| LCH   | pneumaticcraft             | 1.12.2-0.9.3-324         | pneumaticcraft-repressurized-1.12.2-0.9.3-324.jar | None                                     |
	| LCH   | projectred-core            | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar               | None                                     |
	| LCH   | projectred-integration     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCH   | projectred-transmission    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar        | None                                     |
	| LCH   | projectred-fabrication     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar        | None                                     |
	| LCH   | projectred-expansion       | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| LCH   | projectred-relocation      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| LCH   | projectred-transportation  | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar         | None                                     |
	| LCH   | questbook                  | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                          | None                                     |
	| LCH   | randomtweaks               | 1.12.2-2.4.3.2           | randomtweaks-1.12.2-2.4.3.2.jar                   | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCH   | resourceloader             | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | simple_trophies            | 1.1.0                    | simpletrophies-1.1.0.jar                          | None                                     |
	| LCH   | sourcebottles              | 1.0.1                    | SourceBottles-1.0.2.jar                           | None                                     |
	| LCH   | spikemod                   | 1.12-2.1.0               | spikemod-1.12-2.1.0.jar                           | None                                     |
	| LCH   | bq_standard                | @VERSION@                | StandardExpansion-3.4.148.jar                     | None                                     |
	| LCH   | storagedrawers             | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                   | None                                     |
	| LCH   | theoneprobe                | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                       | None                                     |
	| LCH   | tinkersjei                 | 1.0                      | tinkersjei-1.0.jar                                | None                                     |
	| LCH   | tinkertoolleveling         | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
	| LCH   | tipthescales               | 1.0.4                    | TipTheScales-1.12.2-1.0.4.jar                     | None                                     |
	| LCH   | tlauncher_custom_cape_skin | 1.4                      | tlskincape_1.12.2-1.4.jar                         | None                                     |
	| LCH   | toastcontrol               | 1.8.0                    | Toast Control-1.12.2-1.8.0.jar                    | None                                     |
	| LCH   | topaddons                  | 1.12.2-1.10.1            | topaddons-1.12.2-1.10.1.jar                       | None                                     |
	| LCH   | ts2k16                     | 1.2.10                   | TS2K16-1.2.10.jar                                 | None                                     |
	| LCH   | voidislandcontrol          | 1.5.3                    | voidislandcontrol-1.5.3.jar                       | None                                     |
	| LCH   | wct                        | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar       | None                                     |
	| LCH   | reauth                     | 3.6.0                    | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LCH   | justthetips                | 1.12-1.0.1.1             | justthetips-1.12-1.0.1.1.jar                      | None                                     |
	| LCH   | mysticallib                | 1.12.2-1.1.1             | mysticallib-1.12.2-1.1.1.jar                      | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
  net.elnounch.mc.biggerpacketsplz.BiggerPacketsPlzClassTransformer
RandomPatches (randompatches-1.12.2-1.15.0.2.jar)
  com.therandomlabs.randompatches.core.RPTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8681' Renderer: 'Intel(R) UHD Graphics 600'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8681
	OpenGlRenderer: Intel(R) UHD Graphics 600
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by Nedelosk** [comment] 2021-05-27 10:34
Duplicate of #666

**Closed as completed by Nedelosk** 2021-05-27 10:34 UTC
Labels: duplicate
