### ISSUE TITLE
Crash on Launch, ItemHiveFrame

### ISSUE THREAD

**Issue by cjmlax** [ForestryMC/Binnie#342] opened 2017-11-14 18:40 UTC
Playing on TPPI2 modpack, launching from Twitch launcher. TPPI2 version 1.0.2, Forge version 10.13.4.1614, MC version 1.7.10, Binnie's Mod version 2.0.22.7. I had been playing with an out-of-date version of my mods, so I updated them. I get through forge pre-initialization and then it crashes. The quick text of the crash gives me "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail. Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: binnie/extrabees/apiary/ItemHiveFrame" Attached is the full crach report. Thank you!

[crash-2017-11-14_12.33.04-client.txt](https://github.com/ForestryMC/Binnie/files/1472091/crash-2017-11-14_12.33.04-client.txt)

**Comment by Nedelosk** [comment] 2017-11-14 18:43
Remove BinniePatcher
Duplicate of #181

**Closed as completed by Nedelosk** 2017-11-14 18:43 UTC
Labels: duplicate, 1.7.10

**Comment by cjmlax** [comment] 2017-11-14 18:59
I removed it, but I still receive a crash. Is this due to your mod or not?
[crash-2017-11-14_12.57.31-client.txt](https://github.com/ForestryMC/Binnie/files/1472148/crash-2017-11-14_12.57.31-client.txt)

**Comment by mezz** [comment] 2017-11-15 04:22
The crash you have now is between thaumic energistics and applied energistics.
