### ISSUE TITLE
trees don't drop anything

### ISSUE THREAD

**Issue by chantrykomori** [ForestryMC/Binnie#544] opened 2018-08-10 15:44 UTC
trees from Extra Trees never have their leaves mature, and they never drop fruit. in addition, i'm not sure if this is something intentional or not, but date palms and papaya trees never respawn their hanging fruit.

**Comment by Nedelosk** [comment] 2018-08-10 19:33
Duplicate of #404

**Closed as completed by Nedelosk** 2018-08-10 19:33 UTC
Labels: duplicate
