### ISSUE TITLE
Latest version causing server crashes

### ISSUE THREAD

**Issue by inspiiree** [ForestryMC/Binnie#628] opened 2020-01-29 21:58 UTC
```
[19:47:04] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at forestry.arboriculture.genetics.TreeGrowthHelper.hasSufficientSaplingsAroundSapling(TreeGrowthHelper.java:65) ~[TreeGrowthHelper.class:?]
	at forestry.arboriculture.genetics.TreeGrowthHelper.canGrow(TreeGrowthHelper.java:20) ~[TreeGrowthHelper.class:?]
	at forestry.arboriculture.genetics.Tree.canGrow(Tree.java:167) ~[Tree.class:?]
	at binnie.extratrees.gen.BinnieWorldGenTree.canGrow(BinnieWorldGenTree.java:62) ~[BinnieWorldGenTree.class:?]
	at binnie.extratrees.gen.BinnieWorldGenTree.generate(BinnieWorldGenTree.java:115) ~[BinnieWorldGenTree.class:?]
	at forestry.arboriculture.tiles.TileSapling.tryGrow(TileSapling.java:99) ~[TileSapling.class:?]
	at forestry.arboriculture.tiles.TileSapling.onBlockTick(TileSapling.java:50) ~[TileSapling.class:?]
	at forestry.arboriculture.blocks.BlockTreeContainer.updateTick(BlockTreeContainer.java:44) ~[BlockTreeContainer.class:?]
	at net.minecraft.block.Block.randomTick(Block.java:508) ~[aow.class:?]
	at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:476) ~[oo.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:225) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more
```

Server keeps crashing to this error :/

**Comment by Nedelosk** [comment] 2020-02-15 09:08
Duplicate of #626

**Closed as completed by Nedelosk** 2020-02-15 09:08 UTC
Labels: duplicate
