### ISSUE TITLE
[1.12.2]v2.5.0.b168 Module/mod (Genetics) cannot be disabled

### ISSUE THREAD

**Issue by Cronosus** [ForestryMC/Binnie#551] opened 2018-09-18 22:05 UTC
Little problem with disabling module/s (not tested all), but genetics cannot be disabled, even i set it to false, its still in game.

**Comment by CrankySupertoonArchive** [comment] 2018-09-19 20:37
Also this is kind of important because my botany module is crashing and i can not disable it either

https://paste.ee/p/xTEwB

**Comment by CrankySupertoonArchive** [comment] 2018-09-19 20:41
Sorry if i kind of hijacked this thread.

**Comment by Nedelosk** [comment] 2018-11-09 13:24
Duplicate of #305

**Closed as completed by Nedelosk** 2018-11-09 13:24 UTC
Labels: duplicate
