### ISSUE TITLE
Merry Bee issues

### ISSUE THREAD

**Issue by Toapoint** [ForestryMC/Binnie#379] opened 2017-12-27 13:52 UTC
Everytime I try to breed a merry bee, this is the error that comes up on our server log. It refuses to breed this bee! :(

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/27/17 6:34 AM
Description: Exception in server tick loop

java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:295)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:252)
	at forestry.apiculture.multiblock.AlvearyController.updateServer(AlvearyController.java:233)
	at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:445)
	at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:81)
	at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:31)
	at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_553_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by temp1011** [comment] 2017-12-30 18:55
Do you think this is similar to https://github.com/ForestryMC/Binnie/issues/370? The trace seems quite similar.

**Comment by Nedelosk** [comment] 2018-01-23 15:34
Duplicate of #370

**Closed as completed** 2018-01-23 15:34 UTC
Labels: duplicate
