### ISSUE TITLE
Crash on mouseover error icon in incubator

### ISSUE THREAD

**Issue by HammerDave** [ForestryMC/Binnie#286] opened 2017-08-23 17:17 UTC
My incubator is not processing and has a red diamond bang icon.
If I mouse over that to see what is wrong, a client crash ensues.
MC 1.11.2 binne-mods 2.1.0.38.jar

java.lang.NullPointerException: Rendering screen
	at binnie.core.machines.errors.ErrorState.toString(ErrorState.java:63)
	at binnie.core.gui.minecraft.control.ControlErrorState.getTooltip(ControlErrorState.java:97)
	at binnie.core.gui.minecraft.Window.getTooltip(Window.java:124)
	at binnie.core.gui.minecraft.GuiCraftGUI.func_73863_a(GuiCraftGUI.java:109)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by mezz** [comment] 2017-08-24 04:19
Thanks for the report!
I'm not able to reproduce this bug. Can you take a screenshot of your incubator gui and include the full crash log?

**Comment by HammerDave** [comment] 2017-08-24 06:39
Images at http://imgur.com/a/hJDbm
The problem occurs if the mouse goes over the red diamond.
That widget does not have a text filled in so toString tries to use a null pointer.
One image is before I fill things in, 2nd image is after adding materials.

The machine processes one cycle and then stops.  25mb of water is used and 25mb of liquid growth medium is produced and piped out.   (I guess that's a bug too since it has a valid recipe but isn't processing it).

[crash-2017-08-23_10.21.48-client.txt](https://github.com/ForestryMC/Binnie/files/1247945/crash-2017-08-23_10.21.48-client.txt)

Edit:  Figured out some more info.  It wasn't just one cycle -- the machine ran until water got down to 475mb and then it stopped.  I want to let the water run dry and reuse the same machine to process a different recipe, and it refuses to continue until I give it more water.  So IMO it is indeed two bugs but I'll leave just this one report for now.  :)

**Comment by HammerDave** [comment] 2017-08-24 07:02
Another update.  
I broke the machine in order to use it to do more stuff.
It does the same thing with another recipe -- liquid growth medium + wheat -> bacteria.
Machine stops when input tank reaches 475mb.
I'm pretty sure it's the lack of text accompanying that reason for stoppage.  I don't fancy crashing the client again to find out though lol

**Comment by HammerDave** [comment] 2017-08-25 03:02
Same bug happens with the sequencer if the mouse goes over the red diamond, this time before i could put anything into the machine.

**Comment by mezz** [comment] 2017-08-25 05:53
Looks like this works fine on singleplayer worlds, but I got the crash when connected to a server.
I should have a fix for this soon.

**Closed as completed** 2017-08-25 06:50 UTC
Labels: bug-major
