### ISSUE TITLE
[1.12.1] hives not accessible to other mods

### ISSUE THREAD

**Issue by kristofersokk** [ForestryMC/Binnie#309] opened 2017-09-17 21:42 UTC
In the Modern Skyblock 2 modpack, mod SkyResources 2 uses bee attractor to get bees in a skyblock world. It uses forestry.apiculture.PluginApiculture.getHiveRegistry().getHives() etc to get hives from which bees are gotten. Hence, there's no api for extra bees? maybe add this functionality so that this mod can get extra bees hives and bees from them

**Comment by Nedelosk** [comment] 2018-11-09 20:32
Duplicate of #459

**Closed as completed by Nedelosk** 2018-11-09 20:32 UTC
Labels: duplicate
