### ISSUE TITLE
cannot disable modules.

### ISSUE THREAD

**Issue by Zer0Lyfe** [ForestryMC/Binnie#369] opened 2017-12-15 08:44 UTC
Cannot disable some of the modules like trees and botany
![2017-12-15_16 42 04](https://user-images.githubusercontent.com/28994351/34033857-feae385c-e1b6-11e7-9333-504c3b96020c.png)
![2017-12-15_16 42 27](https://user-images.githubusercontent.com/28994351/34033858-fee4ecc6-e1b6-11e7-8e21-ba6cf5aab503.png)
![image](https://user-images.githubusercontent.com/28994351/34033875-16d5498e-e1b7-11e7-83ae-ab40d90ea366.png)

**Comment by Zer0Lyfe** [comment] 2017-12-15 08:51
Recipes are still visible after a couple of restarts and the configs are the same as above.
![2017-12-15_16 48 58](https://user-images.githubusercontent.com/28994351/34034124-2029059c-e1b8-11e7-9357-f28cfabe0174.png)

**Comment by temp1011** [comment] 2017-12-29 22:04
This is interesting.

Disabling Genetics loads all blocks and recipes and the machines are craftable in survival but right click on machines does nothing (no gui loaded?) and right click with the analyst does this  [crash-2017-12-29_22.00.54-client.txt](https://github.com/ForestryMC/Binnie/files/1593937/crash-2017-12-29_22.00.54-client.txt). So disabling a module at least partly works but the recipes are still loaded and the base blocks so I guess this is similar/same to https://github.com/ForestryMC/Binnie/issues/360.

EDIT: https://github.com/ForestryMC/Binnie/issues/305 they know and are working on a fix.

EDIT2?: I think the current way to delete modules comes down to deleting modules from the Binnie's jar so either requires building the mod yourself or extracting the main .jar file https://github.com/ForestryMC/Binnie/issues/245

**Comment by Nedelosk** [comment] 2018-11-09 16:45
Duplicate of #305

**Closed as completed by Nedelosk** 2018-11-09 16:45 UTC
Labels: duplicate
