### ISSUE TITLE
[1.7.10] Crash with binniefixes

### ISSUE THREAD

**Issue by Neuromantix** [ForestryMC/Binnie#193] opened 2017-07-11 14:47 UTC
Forestry 4.2.16.64 minecraft 1.7.10 no binie patcher 
Crash
Log https://pastebin.com/mnRT7c8U

2.14 with patcher works good

**Comment by KorDum** [comment] 2017-07-11 18:51
> binniefixes{1.0.1} [More Binnie Fixes] (minecraft.jar)

Remove this. Is the problem resolved?

**Comment by mezz** [comment] 2017-07-12 02:32
Please report this to binniefixes, they can include their fixes in the actual mod with a PR here.

**Comment by KorDum** [comment] 2017-07-12 06:42
@mezz MoreBinnieFixes resolved [this issue](https://github.com/ForestryMC/Binnie/issues/69). I wrote message to author.

**Comment by CombatZAK** [comment] 2017-07-12 12:40
Hello. I am the author of **More Binnie Fixes**. My apologies for taking so long to reply. KorDum had left a message for me some time ago. Entirely my fault. The cause of the crash has already been traced - related to Binnie's code referencing unregistered items when certain modules in Forestry are turned off in config. The fix for it is pretty simple; just a check to see if the modules are turned on before using items in recipes.

I would be happy to roll my fixes into this repo. I will work on a PR today.

Cheers

**Comment by CombatZAK** [comment] 2017-07-12 12:50
Addendum: it's unsurprising my mod would cause a crash with this repo. It is a class editor, meant to inject changes into Binnie's classes during load. The changes were somewhat surgical and relied on Binnie's last official release of his mods. Further changes to his code would have rendered More Binnie Fixes incompatible when Forestry team took over support of his mods. The log shared by @Neuromantix shows problems with the stack during load of the Genetics class - which is indicative of a problem with the instruction changes my mod applies. @mezz is correct in that applying the changes to managed code here should clear this up.

**Comment by Neuromantix** [comment] 2017-07-12 12:59
Without More Binnie Fixes works good (game and world loaded, but I don't make all of blocks ingame tests)

**Comment by KorDum** [comment] 2017-07-12 13:15
@CombatZAK big thanks for reply!

**Comment by zahess** [comment] 2017-07-12 15:07
@Neuromantix, **More Binnie Fixes** repairs a startup crash related to running Binnie's mods with Forestry Butterflies module disabled. If you are getting past startup with **More Binnie Fixes** removed, I assume you have not disabled Butterflies. So you can work around this issue by removing my mod from your environment - there should be no ill effects for doing so.

**Comment by CombatZAK** [comment] 2017-07-12 15:09
@Neuromantix, **More Binnie Fixes** repairs a startup crash related to running Binnie's mods with Forestry Butterflies module disabled. If you are getting past startup with **More Binnie Fixes** removed, I assume you have not disabled Butterflies. So you can work around this issue by removing my mod from your environment - there should be no ill effects for doing so.

(Originally posted in incorrect GitHub profile, that's what I get for posting from the office)

**Comment by CombatZAK** [comment] 2017-07-12 23:53
PR #201 submitted for review at your convenience. When this gets merged and released, I will make a note on my curse page that **More Binnie Fixes** is deprecated.

**Comment by KorDum** [comment] 2017-07-13 06:20
Thanks for help!

**Closed as completed by KorDum** 2017-07-13 06:20 UTC
Labels: question, 1.7.10
