### ISSUE TITLE
[1.12.2] Marble Hives not spawning

### ISSUE THREAD

**Issue by Boomflex** [ForestryMC/Binnie#535] opened 2018-06-20 10:04 UTC
Seeing this in:

FTB Revelations v2.0.0 also.

Binnie's Mods: v1.12.2-2.5.0.165

Extrabees main.conf reads

Sets the worldgen spawn chance for marble hives. [range: 0 ~ 10, default: 2]
I:marbleHiveRate=2

**Comment by Nedelosk** [comment] 2018-06-20 12:33
Duplicate of #274

**Closed as completed by Nedelosk** 2018-06-20 12:33 UTC
Labels: duplicate
