### ISSUE TITLE
[1.12.2] Compartment Recipes Can't Be Removed

### ISSUE THREAD

**Issue by TheLimePixel** [ForestryMC/Binnie#553] opened 2018-09-22 14:53 UTC
Using CraftTweaker, Compartments' recipes simply can't be removed. This issue was posted months ago and I was disappointed to find out this was still the case. It's just a really big issue for pack makers, such as myself.

**Comment by Nedelosk** [comment] 2018-09-22 15:22
Duplicate of #308

**Closed as completed by Nedelosk** 2018-09-22 15:22 UTC
Labels: duplicate
