### ISSUE TITLE
[1.12.2] Fluid/Power not rendering in Brewery GUI

### ISSUE THREAD

**Issue by SnowShock35** [ForestryMC/Binnie#344] opened 2017-11-14 19:13 UTC
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.2542
- Forestry 1.12.2-5.7.0.212
- Binnie's Mods 1.12.2-5.0.96
- The One Probe 1.12-1.4.19

#### Issue Description

The internal buffers for Power/Fluids isn't shown inside the Brewers GUI. Despite having power and being completely filled. This is shown in the screenshots below.

#### Issue Media

![Issue Media #1](https://ss.blamesnow.co.uk/2017/11/1510686658-b936f214.png)

![Issue Media #2](https://ss.blamesnow.co.uk/2017/11/1510686676-8e7bbdc6.png)

![Issue Media #3](https://ss.blamesnow.co.uk/2017/11/1510686731-070457c3.gif)

**Comment by SnowShock35** [comment] 2017-11-17 08:49
Appears to be fixed. Was it? I don't recall seeing this fixed in changelogs?

**Comment by TheLimePixel** [comment] 2017-11-17 12:30
The same is happening with the Incubator by the looks of it:
![image](https://user-images.githubusercontent.com/25333164/32947298-8008b012-cb9b-11e7-87d8-53ad4e2d8882.png)
![image](https://user-images.githubusercontent.com/25333164/32947307-87823304-cb9b-11e7-9a94-11e27faf4416.png)

**Comment by mezz** [comment] 2017-11-20 07:54
Thanks for the report!
I am not able to reproduce this reliably yet. I saw it happen on the BTM server sometimes, but not locally.

**Comment by SnowShock35** [comment] 2017-11-20 17:21
Yeah definitely still have this happening? Is there perhaps something related to our environments that might cause it? E.g. Java Version or perhaps other mods? or maybe even certain version of Forge?

**Comment by toaran** [comment] 2017-11-29 00:05
I have the same problem with all the binnie machines... the one Probe shows RF but the machines GUI shows 0/0 RF  and is not working
I play the Modern Skyblock 2 modpack also updated the mod to the latest version available on curse.. no luck. I also tired it with only forestry, Binnies and JEI ... no luck. here is a log with a ton of errors.. maybe that helps: https://filebin.ca/3iu3A6kZmeoh/latest.log

It happens on our Server and also local

any ideas? any log i can share or debug output?

**Comment by mezz** [comment] 2017-11-30 05:52
Thanks for the log, this appears to be caused by some recent fixes in Forge networking code.

**Comment by mezz** [comment] 2017-11-30 06:28
This should be fixed in the latest version of Binnie's, building now.

**Closed as completed** 2017-11-30 06:27 UTC
Labels: bug-major, core
