### ISSUE TITLE
[1.12.2] [Question] Wooden Gear

### ISSUE THREAD

**Issue by Draskh** [ForestryMC/Binnie#374] opened 2017-12-24 14:33 UTC
If binnies Mods are present in my mod pack the normal wooden gear of Applied Energistics is deactivated. I try now to figure out which mod that does. 
Does Binnie's Mods have a function that replaces wooden gears?

**Comment by mezz** [comment] 2017-12-24 20:40
Looks like the Proven Gear is oredict "gearWood".
I will remove this oredict name, it's not really correct since the Proven Gears are a lot more expensive.

**Comment by mezz** [comment] 2017-12-24 20:41
Duplicate of https://github.com/ForestryMC/Binnie/issues/359

**Closed as completed by mezz** 2017-12-24 20:41 UTC
Labels: duplicate

**Comment by Draskh** [comment] 2017-12-25 03:36
Everything works fine now, thanks!
