### ISSUE TITLE
Combined Ceramic Blocks seem to not render

### ISSUE THREAD

**Issue by asiekierka** [ForestryMC/Binnie#402] opened 2018-01-26 19:01 UTC
Binnie's Mods 2.5.0.112, Forge .2599, tested with and without various combinations of other mods, in particular OptiFine and FoamFix are not involved.

![](https://img.asie.pl/hIV2)

**Comment by mezz** [comment] 2018-01-27 06:47
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/Binnie/issues/368

**Closed as completed by mezz** 2018-01-27 06:47 UTC

**Comment by asiekierka** [comment] 2018-01-27 07:04
Oh, sorry.
