### ISSUE TITLE
Using acclimatiser on queens will cause server/client crash.  Ver  2.5.0.112

### ISSUE THREAD

**Issue by Electrofried** [ForestryMC/Binnie#415] opened 2018-02-24 22:42 UTC
So if you use the acclimatiser on a queen, then stick it in a hive to work, it will cause a server crash when the hive does a work tick. See attached crash log for more details.

 Ver  2.5.0.112

[crash-2018-02-24_03.59.46-server.txt](https://github.com/ForestryMC/Binnie/files/1755392/crash-2018-02-24_03.59.46-server.txt)
[crash-2018-02-22_07.39.25-server.txt](https://github.com/ForestryMC/Binnie/files/1755393/crash-2018-02-22_07.39.25-server.txt)
[crash-2018-02-14_05.06.52-server.txt](https://github.com/ForestryMC/Binnie/files/1755394/crash-2018-02-14_05.06.52-server.txt)

**Comment by Nedelosk** [comment] 2018-02-24 23:14
Duplicate of #370

**Closed as completed by Nedelosk** 2018-02-24 23:14 UTC
Labels: duplicate
