### ISSUE TITLE
[1.12.2] Crash on dedicated server

### ISSUE THREAD

**Issue by KindarConrath** [ForestryMC/Binnie#350] opened 2017-11-20 20:37 UTC
MC 1.12.2
binnies [100 & 101]

Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Binnie's Genetics (genetics)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft

doesn't happen on 97

**Comment by Eggonomicon** [comment] 2017-11-21 02:14
I am experiencing the same issue,
MC: 1.12.2
Forge Version: forge-1.12.2-14.23.0.2550-universal
Binnies Mods: 101

Link to Error: https://pastebin.com/2x4JtJ7m

Seems to be an issue with the Genetics portion.
I do have the Gendustry mod installed.

Thank you,
Eggonomicon

**Comment by TheQKnight** [comment] 2017-11-21 04:51
Same here. Genetics seems to be causing it.

**Comment by SamboyCoding** [comment] 2017-11-21 18:51
It's caused by [this line](https://github.com/ForestryMC/Binnie/blob/master-MC1.12/genetics/src/main/java/binnie/genetics/item/ItemSequence.java#L39) attempting to load the current Locale on the server - which in turn calls Minecraft.getMinecraft() on the server, which crashes.

**Comment by mezz** [comment] 2017-11-22 06:10
Thanks for the report!
Fixed in the next version.

**Closed as completed** 2017-11-22 06:10 UTC
Labels: bug-major
